# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ramblings of a Squirrel
email: HarlemSquirrel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Things may get a little nuts...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://harlemsquirrel.github.io" # the base hostname & protocol for your site
twitter_username: HarlemSquirrel
github_username:  HarlemSquirrel

# Build settings
markdown: kramdown

# Plugins
gems: [jekyll-paginate]

# Outputting
paginate: 10

liquid:
  error_mode: warn
