# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ramblings of a Squirrel
email: wittyman37@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This is the blog of a web developer, musician, educator, and open source enthusiest.
  Oh, and keep away from my acorns!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kevinwmccormack
github_username:  HarlemSquirrel

# Build settings
markdown: kramdown
